### ISSUE TITLE
Add new contributors to this io.gdevelop.ide repository

### ISSUE THREAD

**Issue by 4ian** [flathub/io.gdevelop.ide#1]
Hi,

Any chance a flathub admin (@barthalion maybe?) can add @alexandresi and @clementpasteau as collaborators to this repository?

I tried to check if there is a process for such requests but could not find anything.

Thanks!

**Comment by barthalion** [comment]
Hi, just sent out invitations. Please make sure to accept them within a week. Thanks!

**Comment by 4ian** [comment]
Thank you!
